language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -U -r requirements.txt"
  - "pip install ."
  - "pip install -U pytest"
# command to run tests
script: py.test
